---
bin_dir: /usr/local/bin
atom_upgrade_all: False
atom_packages:
  - language-ansible
  - atom-beautify
  - block-comment
  - file-icons
  - git-history
  - git-log
  - git-projects
  - git-plus
  - language-generic-config
  - language-nagios
  - merge-conflicts
  - open-recent
  - markdown-writer
  - pigments
  - project-manager
  - qolor

vscode_packages:
  - DavidAnson.vscode-markdownlint
  - HookyQR.beautify
  - PeterJausovec.vscode-docker
  - akamud.vscode-theme-onedark
  - donjayamanne.python
  - emilast.LogFileHighlighter
  - file-icons.file-icons
  - haaaad.ansible
  - jasonn-porch.gitlab-mr
  - magicstack.MagicPython
  - ms-vscode.PowerShell
  - robertohuertasm.vscode-icons
  - tht13.python
  - wholroyd.jinja
  - yzane.markdown-pdf